name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CI: true
      APP_ENV: test
    services:
      postgres:
        image: postgres:16.1
        ports: ["5432:5432"]
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.3.0"

    steps:
      - uses: actions/checkout@v4
      - name: Install postgres client dependencies
        run: sudo apt-get install libpq-dev
      - name: Copy .env.test file
        run: cp .env.test.template .env.test
      - name: Load .env.test file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./
          mode: test
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Create database and running migrations
        run: |
          bundle exec rake auction_fun_core:db:create_database[postgres]
          bundle exec rake auction_fun_core:db:migrate
        env:
          POSTGRES_HOST: localhost
      - name: Run lint
        run: bundle exec standardrb
      - name: Run suite
        run: bundle exec rspec spec/ --color --format progress
